### ISSUE TITLE
Map tile images are broken

### ISSUE THREAD

**Issue by writele** [CodeForWinstonSalem/finda#5]
The provider of the map's tile images no longer works, so we will have to find a new map tile provider to implement the map in Finda. This is true across all implementations of Finda. (See, for example, https://codeforgso.github.io/finda/ and http://codeforboston.github.io/finda/).

Original map tile provider:
http://korona.geog.uni-heidelberg.de

**Comment by writele** [comment]
At Brian's suggestion, I'm going to look into leaflet js as a possible solution.

**Comment by buzzbombnc** [comment]
It's working this morning over at the CFWS pages (http://codeforwinstonsalem.github.io/finda), but not on CfGSO.  Please note that the map provider CFWS is using is different than CfGSO, but both use Leaflet.js at their core.

The configuration setting is found in `src/ui/map.js` on line 13.

**Comment by writele** [comment]
You're right. It looks like it was just down temporarily yesterday evening. The images at http://korona.geog.uni-heidelberg.de are loaded now.
